version: '3.4'

services:  
  autheticationservice:
    image: ${DOCKER_REGISTRY-}autheticationservice
    build:
      context: .
      dockerfile: AutheticationService\Dockerfile


  gatewayservices:
    image: ${DOCKER_REGISTRY-}gatewayservices
    build:
      context: .
      dockerfile: GatewayServices\Dockerfile

