version: '3.4'

services:
  webapplication2:
    image: ${DOCKER_REGISTRY-}webapplication2
    build:
      context: .
      dockerfile: WebApplication2\Dockerfile

  autheticationservice:
    image: ${DOCKER_REGISTRY-}autheticationservice
    build:
      context: .
      dockerfile: AutheticationService\Dockerfile


  gatewayservices:
    image: ${DOCKER_REGISTRY-}gatewayservices
    build:
      context: .
      dockerfile: GatewayServices\Dockerfile

